language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run build:js
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: 
    master: chessreact
    develop: chessreact-dev
  skip_cleanup: true
